### ISSUE TITLE
ERR_250_ENTRY_ALREADY_EXISTS ou=system already exists 

### ISSUE THREAD

**Issue by shashanksheela** [ome/apacheds-docker#15]
we have a docker-compose.yml will some services in which we are using this image for one service as below
version: '3.6'
services:
  ldap:
       image: openmicroscopy/apacheds
       ports:
        - "10389:10389"
        - "10636:10636"
        - "60088:60088"
        - "60464:60464"
        - "9090:8080"
        - "8443:8443"
        volumes:
           - ./myconfig.ldif:/bootstrap/conf/config.ldif:ro
           - myconfigdata:/var/lib/apacheds
      //other services//
volumes:
myconfigdata:

The first time it starts perfectly but later on, it gives ERR_250_ENTRY_ALREADY_EXISTS ou=system already exists and gets terminated. Kindly help us.

full logs
{"log":"Cleaning up /var/lib/apacheds/default/run/apacheds-default.pid\n","stream":"stdout","time":"2018-06-21T07:38:21.869608788Z"}
{"log":"Starting ApacheDS - default...\n","stream":"stdout","time":"2018-06-21T07:38:24.91363281Z"}
{"log":"[07:39:43] ERROR [org.apache.directory.server.wrapper.ApacheDsTanukiWrapper] - Failed to start the service.\n","stream":"stdout","time":"2018-06-21T07:39:43.894071776Z"}
{"log":"org.apache.directory.api.ldap.model.exception.LdapEntryAlreadyExistsException: ERR_250_ENTRY_ALREADY_EXISTS ou=system already exists!\n","stream":"stdout","time":"2018-06-21T07:39:43.894094076Z"}
{"log":"\u0009at org.apache.directory.server.core.partition.impl.btree.AbstractBTreePartition.add(AbstractBTreePartition.java:698)\n","stream":"stdout","time":"2018-06-21T07:39:43.894106484Z"}
{"log":"\u0009at org.apache.directory.server.core.DefaultDirectoryService.initializeSystemPartition(DefaultDirectoryService.java:1764)\n","stream":"stdout","time":"2018-06-21T07:39:43.894110423Z"}
{"log":"\u0009at org.apache.directory.server.core.DefaultDirectoryService.initialize(DefaultDirectoryService.java:1824)\n","stream":"stdout","time":"2018-06-21T07:39:43.894113929Z"}
{"log":"\u0009at org.apache.directory.server.core.DefaultDirectoryService.startup(DefaultDirectoryService.java:1251)\n","stream":"stdout","time":"2018-06-21T07:39:43.89411724Z"}
{"log":"\u0009at org.apache.directory.server.ApacheDsService.initDirectoryService(ApacheDsService.java:364)\n","stream":"stdout","time":"2018-06-21T07:39:43.89412127Z"}
{"log":"\u0009at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:197)\n","stream":"stdout","time":"2018-06-21T07:39:43.894125062Z"}
{"log":"\u0009at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:153)\n","stream":"stdout","time":"2018-06-21T07:39:43.894128718Z"}
{"log":"\u0009at org.apache.directory.server.wrapper.ApacheDsTanukiWrapper.start(ApacheDsTanukiWrapper.java:175)\n","stream":"stdout","time":"2018-06-21T07:39:43.894146597Z"}
{"log":"\u0009at org.tanukisoftware.wrapper.WrapperManager$12.run(WrapperManager.java:2788)\n","stream":"stdout","time":"2018-06-21T07:39:43.894150444Z"}

**Comment by shashanksheela** [comment]
We have tried by setting APACHEDS_INSTANCE still, the issue persists
environment:
           APACHEDS_INSTANCE: "myinstance"

**Comment by joshmoore** [comment]
Hi @shashanksheela . Thanks for the compose example. I may end up adding that to the repo if you don't mind. I'm currently testing with:

```
version: "3.3"
services:
  ldap:
    image: "openmicroscopy/apacheds:0.6.0"
    ports:
      - "10389:10389"
      - "10636:10636"
      - "60088:60088"
      - "60464:60464"
      - "9090:8080"
      - "8443:8443"
    volumes:
      - ./myconfigdata:/var/lib/apacheds
      # ./myconfig.ldif:/bootstrap/conf/config.ldif:ro
```

since I don't have your config file. However, this is re-starting fine for me:

```
$ docker-compose up
Starting ldap_ldap_1 ...
Starting ldap_ldap_1 ... done
Attaching to ldap_ldap_1
ldap_1  | Starting ApacheDS - default...
ldap_1  | [09:31:44] WARN [org.apache.directory.server.core.DefaultDirectoryService] - You didn't change the admin password of directory service instance 'default'.  Please update the admin password as soon as possible to prevent a possible security breach.
^CGracefully stopping... (press Ctrl+C again to force)
Stopping ldap_ldap_1 ... done
```

Is your LDIF file something you could share with me so I could test?

**Comment by joshmoore** [comment]
Hmmm.... I'm not sure what's going on here, @shashanksheela. It's working for me:

 * with/without your LDIF file
 * with the volume set to `myconfigdata` as you have it or in the current directory like `./myconfigdata`

Can you show me a full terminal script of starting a new volume, stopping it, and restarting it, all with the logs?

Edit: by the way:

```
$ docker --version
Docker version 18.03.1-ce, build 9ee9f40
$ docker-compose --version
docker-compose version 1.17.1, build 6d101fb
```

**Comment by shashanksheela** [comment]
step 1:docker-compose up --build ldap
step 2: stopping the server by ctrl+c
step 3: docker-compose up --build ldap
terminal
![image](https://user-images.githubusercontent.com/31468220/41715719-f82d032e-7571-11e8-977d-108c647c9d01.png)

logs
{"log":"'/bootstrap/cache' -\u003e '/var/lib/apacheds/default/cache'\n","stream":"stdout","time":"2018-06-21T11:09:54.145530958Z"}
{"log":"'/bootstrap/conf' -\u003e '/var/lib/apacheds/default/conf'\n","stream":"stdout","time":"2018-06-21T11:09:54.145679135Z"}
{"log":"'/bootstrap/conf/config.ldif' -\u003e '/var/lib/apacheds/default/conf/config.ldif'\n","stream":"stdout","time":"2018-06-21T11:09:54.145717926Z"}
{"log":"'/bootstrap/conf/wrapper-instance.conf' -\u003e '/var/lib/apacheds/default/conf/wrapper-instance.conf'\n","stream":"stdout","time":"2018-06-21T11:09:54.145740993Z"}
{"log":"'/bootstrap/conf/log4j.properties' -\u003e '/var/lib/apacheds/default/conf/log4j.properties'\n","stream":"stdout","time":"2018-06-21T11:09:54.145767203Z"}
{"log":"'/bootstrap/log' -\u003e '/var/lib/apacheds/default/log'\n","stream":"stdout","time":"2018-06-21T11:09:54.145788897Z"}
{"log":"'/bootstrap/ome.ldif' -\u003e '/var/lib/apacheds/default/ome.ldif'\n","stream":"stdout","time":"2018-06-21T11:09:54.145809593Z"}
{"log":"'/bootstrap/partitions' -\u003e '/var/lib/apacheds/default/partitions'\n","stream":"stdout","time":"2018-06-21T11:09:54.145830613Z"}
{"log":"'/bootstrap/run' -\u003e '/var/lib/apacheds/default/run'\n","stream":"stdout","time":"2018-06-21T11:09:54.145851864Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/log' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.17513009Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/partitions' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175201407Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/cache' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175227712Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/ome.ldif' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175248089Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/run' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175268763Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/conf/config.ldif' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175290297Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/conf/wrapper-instance.conf' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175311239Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/conf/log4j.properties' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175331749Z"}
{"log":"changed ownership of '/var/lib/apacheds/default/conf' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175353266Z"}
{"log":"changed ownership of '/var/lib/apacheds/default' from root:root to apacheds:apacheds\n","stream":"stdout","time":"2018-06-21T11:09:54.175374209Z"}
{"log":"Starting ApacheDS - default...\n","stream":"stdout","time":"2018-06-21T11:09:54.459598378Z"}
{"log":"[11:10:16] WARN [org.apache.directory.server.core.DefaultDirectoryService] - You didn't change the admin password of directory service instance 'default'.  Please update the admin password as soon as possible to prevent a possible security breach.\n","stream":"stdout","time":"2018-06-21T11:10:16.83534139Z"}
{"log":"Shutting down...\n","stream":"stdout","time":"2018-06-21T11:10:25.285592319Z"}
{"log":"Terminated\n","stream":"stderr","time":"2018-06-21T11:10:25.285597844Z"}
{"log":"Stopping ApacheDS - default...\n","stream":"stdout","time":"2018-06-21T11:10:25.423492059Z"}
{"log":"Waiting for ApacheDS - default to exit...\n","stream":"stdout","time":"2018-06-21T11:10:30.637276617Z"}
{"log":"Cleaning up /var/lib/apacheds/default/run/apacheds-default.pid\n","stream":"stdout","time":"2018-06-21T11:10:42.430259094Z"}
{"log":"Starting ApacheDS - default...\n","stream":"stdout","time":"2018-06-21T11:10:42.46964659Z"}
{"log":"[11:10:48] ERROR [org.apache.directory.server.wrapper.ApacheDsTanukiWrapper] - Failed to start the service.\n","stream":"stdout","time":"2018-06-21T11:10:48.767227618Z"}
{"log":"org.apache.directory.api.ldap.model.exception.LdapEntryAlreadyExistsException: ERR_250_ENTRY_ALREADY_EXISTS ou=system already exists!\n","stream":"stdout","time":"2018-06-21T11:10:48.767272962Z"}
{"log":"\u0009at org.apache.directory.server.core.partition.impl.btree.AbstractBTreePartition.add(AbstractBTreePartition.java:698)\n","stream":"stdout","time":"2018-06-21T11:10:48.767287027Z"}
{"log":"\u0009at org.apache.directory.server.core.DefaultDirectoryService.initializeSystemPartition(DefaultDirectoryService.java:1764)\n","stream":"stdout","time":"2018-06-21T11:10:48.767296055Z"}
{"log":"\u0009at org.apache.directory.server.core.DefaultDirectoryService.initialize(DefaultDirectoryService.java:1824)\n","stream":"stdout","time":"2018-06-21T11:10:48.767310416Z"}
{"log":"\u0009at org.apache.directory.server.core.DefaultDirectoryService.startup(DefaultDirectoryService.java:1251)\n","stream":"stdout","time":"2018-06-21T11:10:48.767318334Z"}
{"log":"\u0009at org.apache.directory.server.ApacheDsService.initDirectoryService(ApacheDsService.java:364)\n","stream":"stdout","time":"2018-06-21T11:10:48.767325869Z"}
{"log":"\u0009at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:197)\n","stream":"stdout","time":"2018-06-21T11:10:48.767333377Z"}
{"log":"\u0009at org.apache.directory.server.ApacheDsService.start(ApacheDsService.java:153)\n","stream":"stdout","time":"2018-06-21T11:10:48.767340596Z"}
{"log":"\u0009at org.apache.directory.server.wrapper.ApacheDsTanukiWrapper.start(ApacheDsTanukiWrapper.java:175)\n","stream":"stdout","time":"2018-06-21T11:10:48.767347516Z"}
{"log":"\u0009at org.tanukisoftware.wrapper.WrapperManager$12.run(WrapperManager.java:2788)\n","stream":"stdout","time":"2018-06-21T11:10:48.767354839Z"}

**Comment by joshmoore** [comment]
The only thing thing I can think of right now is that it's due to the filesystem settings somehow, i.e. that the final state of the server isn't being flushed to disk.

**Comment by shashanksheela** [comment]
Would changing dockerfile accordingly helps?

**Comment by joshmoore** [comment]
If so, I don't know how. My work in https://github.com/openmicroscopy/apacheds-docker/pull/12 was focused specifically on fixing this restart issue, but for some reasons it's still happening in your environment.

**Comment by shashanksheela** [comment]
So what can I try to make it run?

**Comment by joshmoore** [comment]
Do you have another system that you can try on? Do you have another file system? What's the output of `df`? How did you install docker? What version?

**Comment by shashanksheela** [comment]
docker and docker-compose are at latest versions and using ubuntu 16.04
and df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             8119620        0   8119620   0% /dev
tmpfs            1629240     9736   1619504   1% /run
/dev/sda2      944403884 84320416 812087412  10% /
tmpfs            8146188    34088   8112100   1% /dev/shm
tmpfs               5120        4      5116   1% /run/lock
tmpfs            8146188        0   8146188   0% /sys/fs/cgroup
/dev/sda1         523248     4756    518492   1% /boot/efi
tmpfs            1629240       60   1629180   1% /run/user/1000

**Comment by joshmoore** [comment]
> docker and docker-compose are at latest versions and using ubuntu 16.04

Go ahead and paste the version numbers please.

One thing you might try is:

```
docker-compose up -d
```

and then

```
docker-compose down
```

i.e. don't use Ctrl-C, but I'm really grasping at straws until I can see the problem happen here.

**Comment by shashanksheela** [comment]
Docker version 18.03.1-ce 
compose file format 3.6
docker-compose version 1.21.2

docker-compose down will work because it creates new container

**Comment by joshmoore** [comment]
`docker-compose down will work because it creates new container`

What's the harm in that? Isn't it only the volume that you care about?

**Comment by shashanksheela** [comment]
Actually what usually happens is our app will be running and we run docker-compose up parallely so only necessary apps will get restart

**Comment by joshmoore** [comment]
Ok. I'm not sure how you're using it, but my suggestion wasn't likely to be different than the Ctrl-C anyway.

Just to double check: you're not mounting `myconfigdata` in any other container, correct?

**Comment by shashanksheela** [comment]
yes i am not mounting in any other container

**Comment by joshmoore** [comment]
Unless you think you can show me more of your compose file, I'm not sure I have anything else to go on. You could try taking docker-compose out of the picture and test strictly with a docker image and see if it will work for you.

**Comment by shashanksheela** [comment]
docker image is working perfectly. Anyway, I will just think about alternatives. Thank you @joshmoore for your guidance.

**Comment by joshmoore** [comment]
You're very welcome, @shashanksheela. If you find a solution, please do let us know.  (As a side note: if you happen to also be using kubernetes you could try https://github.com/openmicroscopy/apacheds-k8s-app)
