### ISSUE TITLE
kubernetes customization

### ISSUE THREAD

**Issue by boocup** [ome/apacheds-docker#16]
Trying to launch a container in kubernetes matching the documented docker customization (which works great).   

docker run --name ldap -d -p 389:10389 -e APACHEDS_INSTANCE=yourinstance -v /path/to/your/config.ldif:/bootstrap/conf/config.ldif:ro openmicroscopy/apacheds

has anyone tried something similar to this to get the your own config.ldif into the bootstrap and it launch error free?  

      - image: openmicroscopy/apacheds
        name: ldap-server
        volumeMounts:
        - name: ldap-pvc
          mountPath: /bootstrap/conf/
          subPath: config.ldif
          readOnly: true
        ports:
        - containerPort: 10389
          protocol: TCP
        env:
        - name: APACHEDS_INSTANCE
          value: myLDAP

**Comment by joshmoore** [comment]
@boocup : can you tell us what's not working? This is an example deployment that we've worked with: https://github.com/openmicroscopy/apacheds-k8s-app/blob/d0ec1d476221ef039c6d7bbe57c6e62201036093/k8s/deployment.yml#L24

**Comment by boocup** [comment]
I was trying to mimic the docker customization [ https://hub.docker.com/r/openmicroscopy/apacheds scroll down]which spins up the container and initializes it with a custom config.ldif perfectly.  When I used the k8s yaml above, or variations, it looks like the config.ldif isn't picked up...

'/bootstrap/cache' -> '/var/lib/apacheds/myLDAP/cache'
'/bootstrap/conf' -> '/var/lib/apacheds/myLDAP/conf'
'/bootstrap/log' -> '/var/lib/apacheds/myLDAP/log'
'/bootstrap/ome.ldif' -> '/var/lib/apacheds/myLDAP/ome.ldif'
'/bootstrap/partitions' -> '/var/lib/apacheds/myLDAP/partitions'
'/bootstrap/run' -> '/var/lib/apacheds/myLDAP/run'
'/bootstrap/stagroup.ldif' -> '/var/lib/apacheds/myLDAP/stagroup.ldif'
changed ownership of '/var/lib/apacheds/myLDAP/stagroup.ldif' from root:root to apacheds:apacheds
changed ownership of '/var/lib/apacheds/myLDAP/partitions' from root:root to apacheds:apacheds
changed ownership of '/var/lib/apacheds/myLDAP/ome.ldif' from root:root to apacheds:apacheds
changed ownership of '/var/lib/apacheds/myLDAP/conf' from root:root to apacheds:apacheds
changed ownership of '/var/lib/apacheds/myLDAP/run' from root:root to apacheds:apacheds
changed ownership of '/var/lib/apacheds/myLDAP/cache' from root:root to apacheds:apacheds
changed ownership of '/var/lib/apacheds/myLDAP/log' from root:root to apacheds:apacheds
changed ownership of '/var/lib/apacheds/myLDAP' from root:root to apacheds:apacheds
Starting ApacheDS - myLDAP...
FATAL  | wrapper  | Unable to resolve the full path of the configuration file, /var/lib/apacheds/myLDAP/conf/wrapper-instance.conf: No such file or directory
cat: /var/lib/apacheds/myLDAP/run/apacheds-myLDAP.pid: No such file or directory

...I will checkout the example you kindly shared; I thought I tried something similar, but I'll give it a go. I was kind of headed down that similar track again anyway after posting.

Thanks and all the best!

**Comment by joshmoore** [comment]
No problem. Let us know how it goes.

**Comment by boocup** [comment]
worked great! Thanks!
