### ISSUE TITLE
How to enable schemas on 0.8.0 version?

### ISSUE THREAD

**Issue by bakonyip** [ome/apacheds-docker#23]
Hi,
For previous versions default enabled many default schema, but this 0.8.0 version isn't enable that. I tried this, but i can't do this.
I would like to use latest version, but i can't import my datas from 0.6.0 version, but schemas (example samba) not found.
I am waiting for your help!
Thanks, Peter

**Comment by manics** [comment]
Hi, this repo only packages ApacheDS. If you need help with ApacheDS please see the official website https://directory.apache.org/apacheds/ which also includes details of how to obtain support.
