### ISSUE TITLE
Move to Ubuntu 18.04

### ISSUE THREAD

**Issue by githilman** [ome/apacheds-docker#27]
I think the base image should move to Ubuntu 18.04 since 16.04 EOL this April. And maybe move to openjdk 11 too?

**Comment by joshmoore** [comment]
May require some testing but certainly no objections in principle.

**Comment by githilman** [comment]
I have using this repo for build my apacheds docker for running in kubernetes. My problem is the database always break. The more user stored on LDAP the more often the data break. I have implement backup and secured all my user but the break is too often. Maybe anyone have a tweak for this issue.

**Comment by joshmoore** [comment]
Hi @githilman. Can we separate these two issues. Let's discuss database breakages on #28 and leave this for the ubuntu upgrade.
